name: laa-inquests-api

x-db-user: &db_user postgres
x-db-password: &db_password postgres
x-db-name: &db_name api
x-db-host: &db_host db
x-db-port: &db_port 5432

x-postgres_init_env: &postgres_init_env
  POSTGRES_USER: *db_user
  POSTGRES_PASSWORD: *db_password
  POSTGRES_DB: *db_name
  POSTGRES_PORT: *db_port

x-app_db_env: &app_db_env
  DB_USER: *db_user
  DB_PASSWORD: *db_password
  DB_NAME: *db_name
  DB_HOST: *db_host
  DB_PORT: *db_port

services:
  db:
    container_name: db
    image: postgres:18
    environment:
      <<: *postgres_init_env
    ports:
      - "5436:5432"
    healthcheck:
      test: pg_isready -U postgres -d api
      start_period: 5s
      start_interval: 0.2s
      interval: 30s
      timeout: 3s
      retries: 3

  api:
    container_name: api
    build:
      context: .
      args:
        REQUIREMENTS: "requirements-development.txt"
    command: uvicorn app:api --host 0.0.0.0 --port 8027 --reload
    ports:
      - "8027:8027"
    env_file:
      - path: ../.env.api
        required: false
    environment:
      SECRET_KEY: "TEST_KEY"
      <<: *app_db_env
    volumes:
      - ./app:/home/app/laa-inquests-api/app
      - ./tests:/home/app/laa-inquests-api/tests
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build: .
    container_name: db-migrations
    command: sh -c "alembic upgrade head && python bin/seed.py"
    environment:
      <<: *app_db_env
    depends_on:
      db:
        condition: service_healthy
