"""idds_488_add_claim_evidence

Revision ID: 1d98b6648f95
Revises: 0abbfeb39330
Create Date: 2026-07-28 11:59:37.036768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1d98b6648f95"
down_revision: Union[str, None] = "0abbfeb39330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_evidence",
        sa.Column("claim_evidence_id", sa.Uuid(), nullable=False),
        sa.Column("sds_file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("claim_evidence_id"),
        sa.UniqueConstraint("claim_evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_evidence")
    # ### end Alembic commands ###
