"""Remove_isClientCorrespondenceRecipient

Revision ID: 2f2cfb5eb539
Revises: 9c0ab4f5baa3
Create Date: 2026-08-05 15:16:33.489816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2cfb5eb539'
down_revision: Union[str, None] = '9c0ab4f5baa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'claim_evidence', ['claim_evidence_id'])
    op.drop_column('client', 'is_client_correspondence_recipient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_client_correspondence_recipient', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'claim_evidence', type_='unique')
    # ### end Alembic commands ###
