"""idds_293_add_claim_decision_tables

Revision ID: dee9bbd3102e
Revises: 576bb7f74f01
Create Date: 2026-07-21 15:29:55.208030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dee9bbd3102e"
down_revision: Union[str, None] = "576bb7f74f01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_decision",
        sa.Column("claim_decision_id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("REJECT", "GRANT", "PENDING", name="claimdecisionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
        ),
        sa.PrimaryKeyConstraint("claim_decision_id"),
    )
    op.create_table(
        "decision_reason",
        sa.Column("decision_reason_id", sa.Integer(), nullable=False),
        sa.Column("claim_decision_id", sa.Integer(), nullable=False),
        sa.Column(
            "reason_code",
            sa.Enum(
                "MAX_POA_CLAIMS_EXCEEDED",
                "CLAIM_EXCEEDS_SUBSTANTIVE_COST_LIMIT",
                "APPLICATION_CLAIMS_EXCEED_COST_LIMIT",
                "PROFIT_COST_POA_CLAIM_SUBMITTED_TOO_EARLY",
                name="reasoncode",
            ),
            nullable=False,
        ),
        sa.Column("justification", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_decision_id"],
            ["claim_decision.claim_decision_id"],
        ),
        sa.PrimaryKeyConstraint("decision_reason_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("decision_reason")
    op.drop_table("claim_decision")
    # ### end Alembic commands ###
