apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-inquests-api.fullname" . }}
  labels:
    {{- include "laa-inquests-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-inquests-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-inquests-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-inquests-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "alembic upgrade head && python bin/seed.py"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{ include "laa-inquests-api.app.vars" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ include "laa-inquests-api.app.vars" . | nindent 12 }}
            - name: INQUESTS_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_INQUESTS_API_ENTRA_CONFIG }}
                  key: INQUESTS_API_CLIENT_ID
            - name: INQUESTS_API_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_INQUESTS_API_ENTRA_CONFIG }}
                  key: INQUESTS_API_TENANT_ID
            - name: GOV_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_GOV_NOTIFY_API_KEY }}
                  key: GOV_NOTIFY_API_KEY
            - name: GOV_NOTIFY_APPLICATION_SUBMIT_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_GOV_NOTIFY_TEMPLATE_IDS }}
                  key: GOV_NOTIFY_APPLICATION_SUBMIT_TEMPLATE_ID
            - name: GOV_NOTIFY_APPLICATION_REFUSE_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.env.AWS_SECRETS_GOV_NOTIFY_TEMPLATE_IDS}}
                  key: GOV_NOTIFY_APPLICATION_REFUSE_TEMPLATE_ID
            - name: GOV_NOTIFY_APPLICATION_GRANT_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.env.AWS_SECRETS_GOV_NOTIFY_TEMPLATE_IDS}}
                  key: GOV_NOTIFY_APPLICATION_GRANT_TEMPLATE_ID
            - name: GOV_NOTIFY_CALLBACK_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_GOV_NOTIFY_CALLBACK_BEARER_TOKEN }}
                  key: GOV_NOTIFY_CALLBACK_BEARER_TOKEN
            - name: SDS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_SDS_CONFIG }}
                  key: SDS_BASE_URL
            - name: SDS_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_SDS_CONFIG }}
                  key: sds-tenant-id
            - name: SDS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_SDS_CONFIG }}
                  key: SDS_CLIENT_ID
            - name: SDS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_SDS_CONFIG }}
                  key: SDS_CLIENT_SECRET
            - name: SDS_SCOPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.AWS_SECRETS_SDS_CONFIG }}
                  key: SDS_SCOPE
          ports:
            - name: http
              containerPort: 8027
              protocol: TCP
