import enum


class ClaimType(str, enum.Enum):
    PAYMENT_ON_ACCOUNT = "PAYMENT_ON_ACCOUNT"
    FINAL_BILL = "FINAL_BILL"
    NIL_BILL = "NIL_BILL"


class ClaimStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REJECTED_WITH_AMENDMENT = "REJECTED_WITH_AMENDMENT"


class POAType(str, enum.Enum):
    PROFIT_COST = "PROFIT_COST"
    EXPERT_COST = "EXPERT_COST"
    NON_EXPERT_DISBURSEMENT = "NON_EXPERT_DISBURSEMENT"


class ClaimDecisionStatus(str, enum.Enum):
    REJECT = "REJECT"
    GRANT = "GRANT"
    PENDING = "PENDING"


class ReasonCode(str, enum.Enum):
    MAX_POA_CLAIMS_EXCEEDED = "MAX_POA_CLAIMS_EXCEEDED"
    CLAIM_EXCEEDS_SUBSTANTIVE_COST_LIMIT = "CLAIM_EXCEEDS_SUBSTANTIVE_COST_LIMIT"
    APPLICATION_CLAIMS_EXCEED_COST_LIMIT = "APPLICATION_CLAIMS_EXCEED_COST_LIMIT"
    PROFIT_COST_POA_CLAIM_SUBMITTED_TOO_EARLY = (
        "PROFIT_COST_POA_CLAIM_SUBMITTED_TOO_EARLY"
    )
