name: CI

on:
  push:
    branches:
      - main
  pull_request:
    # From docs: if no activity types are specified, the workflow runs when a pull request is opened or reopened or when the head branch of the pull request is updated.
    paths:
      - "deploy/**"
      - "app/**"
      - "tests/**"
      - "Dockerfile"
      - "compose.yaml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Github deployment environment"
        required: false
        default: "dev"
        type: choice
        options:
          - dev

jobs:
  # code-linting:
  #   name: Code Linting
  #   uses: ./.github/workflows/code-linting.yaml

  snyk:
    name: Snyk scan docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Get Snyk OAuth Token
        id: snyk-auth
        run: |
          TOKEN=$(curl -s -X POST "https://api.snyk.io/oauth2/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.SNYK_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.SNYK_CLIENT_SECRET }}" \
            | jq -r '.access_token')

          echo "SNYK_OAUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Build local Docker image
        run: |
          docker build \
            --tag laa-inquests-api:scan \
            --file Dockerfile .

      - name: Run Snyk to scan Docker image
        uses: snyk/actions/docker@8e119fbb6c251787721d34ba683ed48eba792766
        with:
          image: laa-inquests-api:scan
          args: --docker --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_OAUTH_TOKEN: ${{ env.SNYK_OAUTH_TOKEN }}

      - name: Monitor docker image using Snyk
        continue-on-error: true
        uses: snyk/actions/docker@8e119fbb6c251787721d34ba683ed48eba792766
        env:
          SNYK_OAUTH_TOKEN: ${{ env.SNYK_OAUTH_TOKEN }}
        with:
          command: monitor
          image: laa-inquests-api:scan
          args: --file=Dockerfile --policy-path=.snyk

  unit-tests:
    name: Pytest Unit Tests
    uses: ./.github/workflows/unit-tests.yaml

  build-ghcr:
    name: Build and Push to GHCR
    if: github.ref == 'refs/heads/main'
    needs:
      - unit-tests
    uses: ./.github/workflows/build-ghcr.yaml
    permissions:
      contents: read
      packages: write

  deploy-dev:
    if: ${{ !contains(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    needs:
      - unit-tests
      - snyk
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Deploy to dev
        uses: ./.github/actions/deploy
        with:
          allow-list: ${{ secrets.ALLOW_LIST }}
          app-environment: dev
          db-host: ${{ secrets.DB_HOST}}
          db-name: ${{ secrets.DB_NAME }}
          db-password: ${{ secrets.DB_PASSWORD }}
          db-port: ${{ secrets.DB_PORT }}
          db-user: ${{ secrets.DB_USER }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-region: ${{ vars.ECR_REGION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-sha: ${{ github.sha }}
          github-ref-name: ${{ github.ref_name }}
          github-head-ref: ${{ github.head_ref }}
          image-tag: ${{ github.sha }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          provider-api-base-url: ${{ vars.PROVIDER_API_BASE_URL }}
          provider-api-key: ${{ secrets.PROVIDER_API_KEY }}
          ratelimit_max: ${{ vars.RATE_LIMIT_MAX }}
          ratewindow_ms: ${{ vars.RATE_WINDOW_MS }}
          service_name: ${{ vars.SERVICE_NAME }}
          session_name: ${{ vars.SESSION_NAME}}
          session_secret: ${{ secrets.SESSION_SECRET }}
  notify-slack:
    environment: dev
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: always() && github.ref_name == 'main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Send Slack Notification
        uses: ./.github/actions/notify
        with:
          app-environment: dev
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_UAT }}
          pipeline_status: "${{ job.status }} ${{ join(needs.*.result, ' ') }}"
